frame_names:
  #these frame names are for reference of the odometry node that exists in the fake 
  #namespace and publishes fake odom frames based on the fake odometry it receives from 
  #fake diff encoders
  odom_frame_id: "fake_odom" 
  body_frame_id: "fake_base_link"
  left_wheel_joint: "fake_left_wheel_axel"
  right_wheel_joint: "fake_right_wheel_axel"