wheel:
  width: 0.018 #width of wheels
  radius: 0.033 #radius of wheels
  base: 0.160 #distance between centers of wheels
  encoder_ticks_per_rev: 4096
chassis:
  length: .138 #length of mainlink
  thickness: .178 #thickness of mainlink 
  height: .192 #heigh of chassis
velocity:
  max_trans: 0.22
  max_rot: 2.84 #rad/s
motor:
  no_load_speed: 6.35492 #rad/s speed
  max_power: 265 #plus/minus this is the strongest effort you can request from ESC

freq: 60 #added because odom an fake_encoders rely on this