<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="nuturtlebot">
	<!-- load parameters from yaml -->
	<xacro:property name="width" value= "${load_yaml('$(find nuturtle_description)/config/diff_params.yaml')['wheel']['width']}"/>
	<xacro:property name="radius" value= "${load_yaml('$(find nuturtle_description)/config/diff_params.yaml')['wheel']['radius']}"/>	
	<xacro:property name="base" value= "${load_yaml('$(find nuturtle_description)/config/diff_params.yaml')['wheel']['base']}"/>	
	<xacro:property name="length" value= "${load_yaml('$(find nuturtle_description)/config/diff_params.yaml')['chassis']['length']}"/>	
	<xacro:property name="thickness" value= "${load_yaml('$(find nuturtle_description)/config/diff_params.yaml')['chassis']['thickness']}"/>	
	<xacro:property name="height" value= "${load_yaml('$(find nuturtle_description)/config/diff_params.yaml')['chassis']['height']}"/>	
	<xacro:property name="wheel_axel_offset" value= "${load_yaml('$(find nuturtle_description)/config/diff_params.yaml')['chassis']['wheel_axel_offset']}"/>	
	<!-- macro for making  base_link link -->
	<xacro:macro name="base_link_gen" params="width length height">
		<link name="base_link">
			<visual>
				<origin xyz="${length/2 - radius} 0 0" rpy="0 0 0"/>
				<geometry>
					<box size="${length} ${width} ${height}"/>  
				</geometry>
				<material name="red_guy">
					<color rgba="1 0 0 .75"/>
				</material>
			</visual>
			<collision>
				<origin xyz="${length/2 - radius} 0 0" rpy="0 0 0"/>
				<geometry>
					<box size="${length} ${width} ${height}"/>  
				</geometry>
			</collision>
			<inertial>
				<origin xyz="${length/2 - radius} 0 0" rpy="0 0 0"/>
				<mass value="0.9"/>
				<inertia ixx="${0.9 * 1.0/12.0 * (width * width + height * height)}" ixy="0.0" ixz="0.0" iyy="${0.9 * 1.0/12.0 * (length * length + height * height)}" iyz="0.0" izz="${0.9 * 1.0/12.0 * (length * length + width * width)}"/>
			</inertial>
		</link>
	</xacro:macro>

	<!-- macro for making lidar link -->
	<xacro:macro name="scan_gen" params="radius height">
		<link name="base_scan">
			<visual>
				<origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
				<geometry>
					<cylinder radius="${radius}" length="${height}"/>
				</geometry>
				<material name="purp_guy">
					<color rgba="1 0 1 .75"/>
				</material>
			</visual>
		</link>
	</xacro:macro>


	<!-- macro for making wheel links -->
	<xacro:macro name="wheel_gen" params="name radius width">
		<link name="${name}">
			<visual>
				<origin xyz = "0 0 0" rpy="${pi/2} 0 0"/>
				<geometry>
					<cylinder radius="${radius}" length="${width}"/>  
				</geometry>
				<material name="blue_guy">
					<color rgba="0 0 1 .75"/>
				</material>
			</visual>
			<collision>
				<origin xyz = "0 0 0" rpy="${pi/2} 0 0"/>
				<geometry>
					<cylinder radius="${radius}" length="${width}"/>  
				</geometry>
			</collision>
			<inertial>
				<mass value="0.03"/>
				<inertia ixx="${0.03 * 1.0/12.0 * (3.0 * radius * radius + width * width)}" ixy="0.0" ixz="0.0" izz="${0.03 * 1.0/12.0 * (3.0 * radius * radius + width * width)}" iyz="0.0" iyy="${1.0/2.0 * 0.03 * radius * radius}"/>
			</inertial>
		</link>
	</xacro:macro>

	<!-- macro for making caster -->
	<xacro:macro name="caster_gen" params="name radius">
		<link name="${name}">
			<visual>
				<geometry>
					<sphere radius="${radius}"/>
				</geometry>
				<material name="purp_guy">
					<color rgba="1 0 1 .5"/>
				</material>
			</visual>
			<collision>
				<geometry>
					<sphere radius="${radius}"/>
				</geometry>
			</collision>
<!-- 			<inertial>
				
			</inertial> -->
		</link>
	</xacro:macro>


	<!-- macro for making joints -->
	<xacro:macro name="joint_gen" params="name parent child origin rotate">
		<joint name="${name}" type="continuous">
			<axis xyz="0 1 0"/>
			<parent link="${parent}"/>
			<child link="${child}"/>
			<origin xyz="0 ${origin}  ${-height/2 + wheel_axel_offset}" rpy="0 0 ${rotate}"/>
		</joint>
	</xacro:macro>

	<!-- macro for caster joints -->
	<xacro:macro name="caster_joint" params="name parent child origin_z">
		<joint name="${name}" type="fixed">
			<parent link="${parent}"/>
			<child link="${child}"/>
			<origin xyz="${length/2} 0 ${-height/2 - origin_z + wheel_axel_offset}" rpy="0 0 0"/>
		</joint>
	</xacro:macro>

	<!-- macro for base_scan joint -->
	<xacro:macro name="scan_joint" params="name parent child">
		<joint name="${name}" type="continuous">
			<parent link="${parent}"/>
			<child link="${child}"/>
			<origin xyz="${-radius + length/2} 0 ${height/2}" rpy="0 0 0"/>
		</joint>
	</xacro:macro>


	<xacro:base_link_gen width="${base - width}" length="${length}" height="${height}"/>
	<xacro:wheel_gen radius="${radius}" name="left_wheel" width="${width}"/>
	<xacro:wheel_gen radius="${radius}" name="right_wheel" width="${width}"/>
	<xacro:caster_gen radius="${radius/2}" name="caster1"/>
	<!-- <xacro:scan_gen radius=".03" height=".01"/> -->

	<xacro:joint_gen name="left_wheel_axel" parent="base_link" child="left_wheel" origin="${base/2}" rotate="0"/>
	<xacro:joint_gen name="right_wheel_axel" parent="base_link" child="right_wheel" origin="${-base/2}" rotate="0"/>
	<xacro:caster_joint name="cast_joint1" parent="base_link" child="caster1" origin_z="${radius/2}"/>
	<!-- <xacro:scan_joint name="scan_joint" parent="base_link" child="base_scan"/> -->
	


</robot>