<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="ddiff_drive">
	<!-- load parameters from yaml -->
	<xacro:property name="width" value= "${load_yaml('$(find nuturtle_description)/config/diff_params.yaml')['wheel']['width']}"/>
	<xacro:property name="radius" value= "${load_yaml('$(find nuturtle_description)/config/diff_params.yaml')['wheel']['radius']}"/>	
	<xacro:property name="base" value= "${load_yaml('$(find nuturtle_description)/config/diff_params.yaml')['wheel']['base']}"/>	
	<xacro:property name="length" value= "${load_yaml('$(find nuturtle_description)/config/diff_params.yaml')['chassis']['length']}"/>	
	<xacro:property name="thickness" value= "${load_yaml('$(find nuturtle_description)/config/diff_params.yaml')['chassis']['thickness']}"/>	
	
	<xacro:macro name="base_link_gen" params="width length height">
		<link name="base_link">
			<visual>
				<geometry>
					<box size="${width} ${length} ${height}"/>  
				</geometry>
				<material name="red_guy">
					<color rgba="1 0 0 1"/>
				</material>
			</visual>
			<collision>
				<geometry>
					<box size="${width} ${length} ${height}"/>  
				</geometry>
			</collision>
		</link>
	</xacro:macro>

	<xacro:base_link_gen width="${base - width}" length="${length}" height="${thickness}"/>

</robot>