<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="ddiff_drive">
	<!-- load parameters from yaml -->
	<xacro:property name="width" value= "${load_yaml('$(find nuturtle_description)/config/diff_params.yaml')['wheel']['width']}"/>
	<xacro:property name="radius" value= "${load_yaml('$(find nuturtle_description)/config/diff_params.yaml')['wheel']['radius']}"/>	
	<xacro:property name="base" value= "${load_yaml('$(find nuturtle_description)/config/diff_params.yaml')['wheel']['base']}"/>	
	<xacro:property name="length" value= "${load_yaml('$(find nuturtle_description)/config/diff_params.yaml')['chassis']['length']}"/>	
	<xacro:property name="thickness" value= "${load_yaml('$(find nuturtle_description)/config/diff_params.yaml')['chassis']['thickness']}"/>	
	<!-- macro for making  base_link link -->
	<xacro:macro name="base_link_gen" params="width length height">
		<link name="base_link">
			<visual>
				<geometry>
					<box size="${length} ${width} ${height}"/>  
				</geometry>
				<material name="red_guy">
					<color rgba="1 0 0 .5"/>
				</material>
			</visual>
			<collision>
				<geometry>
					<box size="${length} ${width} ${height}"/>  
				</geometry>
			</collision>
		</link>
	</xacro:macro>

	<!-- macro for making wheel links -->
	<xacro:macro name="wheel_gen" params="name radius width">
		<link name="${name}">
			<visual>
				<geometry>
					<cylinder radius="${radius}" length="${width}"/>  
				</geometry>
				<material name="blue_guy">
					<color rgba="0 0 1 .75"/>
				</material>
			</visual>
			<collision>
				<geometry>
					<cylinder radius="${radius}" length="${width}"/>  
				</geometry>
			</collision>
		</link>
	</xacro:macro>

	<!-- macro for making joints -->
	<xacro:macro name="joint_gen" params="name parent child origin rotate">
		<joint name="${name}" type="continuous">
			<axis xyz="0 0 1"/>
			<parent link="${parent}"/>
			<child link="${child}"/>
			<origin xyz="${-length/4} ${origin}  0" rpy="${pi/2} 0 ${rotate}"/>
		</joint>
	</xacro:macro>

	<!-- generate needed links -->
	<link name="origin">
	</link>

	<xacro:base_link_gen width="${base - width}" length="${length}" height="${thickness}"/>
	<xacro:wheel_gen radius="${radius}" name="wheel1" width="${width}"/>
	<xacro:wheel_gen radius="${radius}" name="wheel2" width="${width}"/>

	<!-- generate joints between links -->
	<joint name="to_base" type="fixed">
		<parent link="origin"/>
		<child link="base_link"/>
		<origin xyz="0 0 ${radius}" rpy="0 0 ${pi/2}"/>
	</joint>
	<xacro:joint_gen name="wheel1_joint" parent="base_link" child="wheel1" origin="${base/2}" rotate="0"/>
	<xacro:joint_gen name="wheel2_joint" parent="base_link" child="wheel2" origin="${-base/2}" rotate="0"/>
	


</robot>